### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by YariKartoshe4ka** [SHRP-Devices/device_samsung_j4lte#1]
Hi! I've tried to compile SHRP, but got this unexpected error:
``` 
  [ 99% 689/690] glob vendor/omni/overlay/common/**/*
  ninja: error: '/home/runner/builder/out/target/product/j4lte/kernel', needed by '/home/runner/builder/out/target/product/j4lte/boot.img', missing and no known rule to make it
  18:28:47 ninja failed with: exit status 1
  
  #### failed to build some targets (01:14 (mm:ss)) #### 
  Error: Process completed with exit code 1.
```
I used stock code and can you help me to fix this issue?
[Clone of repo](https://github.com/YariKartoshe4ka/shrp_recovery_samsung_j4lte) (branch `sdcard-boot`)
[Failed workflow](https://github.com/YariKartoshe4ka/shrp_recovery_samsung_j4lte/runs/3640811078?check_suite_focus=true)

**Comment by blackwidowroms** [comment]
Fixed Kernel Link
